#!/usr/bin/env bash
# This script configures custom host resolutions for localhost and facebook.com

HOSTS_FILE="/etc/hosts"

sed -i '/localhost/d' "$HOSTS_FILE"
sed -i '/facebook.com/d' "$HOSTS_FILE"


echo "127.0.0.2 localhost" >> "$HOSTS_FILE"
echo "8.8.8.8 facebook.com" >> "$HOSTS_FILE"
